import "./globals.css";
import { ProductsProvider } from "@/context/ProductsContext";
import Navbar from "../components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ProductsProvider>
          <header>
            <Navbar />
          </header>
          <main className="py-8">
            {children}
          </main>
        </ProductsProvider>
        <footer className="text-center leading-[3rem]">
          © {new Date().getFullYear()} AsTienda
        </footer>
      </body>
    </html>
  );
}
